name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - env: ${{secrets.COVERALLS_REPO_TOKEN}}
    - name: Install dependencies
      run: |
        pip install coverage coveralls
    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coveralls
